language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t svenharder/reactanddocker -f Dockerfile.dev .

script:
  - docker run -e CI=true svenharder/reactanddocker npm run test