language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t svenharder/reactanddocker -f Dockerfile.dev .

script:
  - docker run -e CI=true svenharder/reactanddocker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-477761403318"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY